// Dicionário de tradução — transcrito integralmente de DICIONARIO_TRADUCAO no script original.
const DICIONARIO_TRADUCAO = {
  'VANITY CASE'                      : 'NECESSAIRE',
  'O - CARD SUPORTE'                 : 'PORTA CARTÃO',
  'BUTTERFLY SUNGLASSES'             : 'OCULOS DE SOL BUTTERFLY',
  'SQUARE SUNGLASSES'                : 'OCULOS DE SOL SQUARE',
  'SHIELD SUNGLASSES'                : 'OCULOS DE SOL SHIELD',
  'PILOT SUNGLASSES'                 : 'OCULOS DE SOL PILOT',
  'O - CARD SUPORTE'                 : 'PORTA CARTÃO',
  'O - ACCESSOIRE DE SAC'            : 'BOLSA',
  'O - PORTE MONNAIE A BAND'         : 'BOLSA',
  'M - MEDIUM CASE'                  : 'BOLSA',
  'EARMUFF'                          : 'PROTETOR DE ORELHA',
  'O - MINI BAG'                     : 'BOLSA',
  'O-MINI BAG'                       : 'BOLSA',
  'SQUARE SCARF'                     : 'LENÇO QUADRADO',
  '1 PIECE SWIMMING SUIT'            : 'MAIO (MALHA OU TECIDO)',
  'ACCESSOIRE VOYAGE'                : 'ACESSORIO DE VIAGEM',
  'ACETATE'                          : 'ACETATO',
  'ACRYLIC'                          : 'ACRILICO',
  'ALUMINUM'                         : 'ALUMINIO',
  'AUTRE FORME SANS CHAINE'          : 'POCHETE',
  'BACK PACK'                        : 'MOCHILA',
  'BAG BOX & EVENING PIECES'         : 'BOLSA',
  'BARRETTE'                         : 'PRESILHA DE CABELO',
  'BASE DU DESSUS'                   : 'BASE SUPERIOR',
  'BATH TOWEL'                       : 'TOALHA DE BANHO',
  'BLOUSE'                           : 'BLUSA OU CAMISA (MALHA OU TECIDO)',
  'BLOUSON'                          : 'JAQUETA',
  'BOATER'                           : 'CHAPEU DE BARQUEIRO',
  'BOTTES'                           : 'BOTAS',
  'BOUCLE'                           : 'FIVELA',
  'BOUTONNAGE'                       : 'ABOTOAMENTO',
  'BOWLING BAG'                      : 'BOLSA',
  'BRACELET'                         : 'BRACELETE',
  'BRAID'                            : 'TRANÇA',
  'BRASS'                            : 'LATAO',
  'BRODERIE'                         : 'BORDADO',
  'BROOCH'                           : 'BROCHE',
  'BUCKET BAG'                       : 'BOLSA',
  'BUTTERFLY SUNGLESSES'             : 'OCULOS DE SOL',
  'BUTTERFLY SUNVIDROES'             : 'OCULOS DE SOL',
  "CALF'S SKIN"                      : 'COURO DE BEZERRO',
  'CALFSKIN'                         : 'COURO DE BEZERRO',
  'CAMELLIA BROCHE'                  : 'BROCHE',
  'CAPE'                             : 'CAPA',
  'CARROT PANT'                      : 'CALÇA',
  'CASHMERE'                         : 'CAXEMIRA',
  'CAT EYE SUNGLASSES'               : 'OCULOS DE SOL',
  'CHOUCHOU'                         : 'ELASTICO DE CABELO',
  'CIGARETTE PANT'                   : 'CALÇA',
  'CLOCHE'                           : 'CHAPEU',
  'CLUTCH BAG'                       : 'BOLSA DE MAO',
  'COAT'                             : 'CASACO COMPRIDO',
  'COL+POIGNETS+BASDECORPS'          : 'GOLA + PUNHOS + PARTE INFERIOR DO CORPO',
  'COLLAR'                           : 'COLARINHO',
  'COMMON METAL'                     : 'METAL COMUM',
  'COTTON'                           : 'ALGODAO',
  'CROUTE DE VEAU'                   : 'CRISTA DE VITELA',
  'CUFFS'                            : 'PUNHOS',
  'CUSHION'                          : 'ALMOFADA',
  'DIVERS MERCH'                     : 'IMÃ DECORATIVO',
  'DOUBLURE ELEMENT'                 : 'REVESTIMENTO DE ELEMENTOS',
  'DOUBLURE POCHE'                   : 'FORRO DO BOLSO',
  'DRESS'                            : 'VESTIDO',
  'DYED LAMB SHEARLING'              : 'COURO DE CORDEIRO TINGIDO',
  'DYED SHEEP SHEARLING'             : 'COURO DE OVELHA TINGIDA',
  'EARRINGS'                         : 'BRINCOS',
  'ELASTANE'                         : 'ELASTANO',
  'ELEMENT 1'                        : 'ELEMENTO 1',
  'ELEMENT 2'                        : 'ELEMENTO 2',
  'ELEMENT 3'                        : 'ELEMENTO 3',
  'ELEMENT 4'                        : 'ELEMENTO 4',
  'ELEMENT 5'                        : 'ELEMENTO 5',
  'EMBROIDERY SUPPORT'               : 'SUPORTE DO BORDADO',
  'EMBROIDERY'                       : 'BORDADO',
  'EMMANCHURE'                       : 'DETALHE',
  'ESPADRILLES'                      : 'ALPARGATAS',
  'ETHYLENE-VINYL ACETATE'           : 'ACETATO DE ETILENO-VINILA',
  'ETHYLENE-VINYL ACETATO'           : 'ETILENO-VINIL ACETATO',
  'FANCY BELT'                       : 'CINTO DE METAL',
  'FASH BTQ HANGER'                  : 'CABIDE',
  'FAUX FUR'                         : 'COURO SINTETICO',
  'FEATHERS'                         : 'PENAS',
  'FIL DE COUTURE'                   : 'LINHA DA COSTURA',
  'FINISHING'                        : 'ACABAMENTO',
  'FLAPBAG WITH HANDLE'              : 'BOLSA COM ALÇA',
  'FLAPBAG'                          : 'BOLSA',
  'FLATS'                            : 'SAPATILHAS',
  'FRAME'                            : 'ARMAÇÃO',
  'FRESH WATER PEARL'                : 'PÉROLA DE ÁGUA DOCE',
  'FULL MANNEQUIN'                   : 'MANEQUIM',
  'GARNET'                           : 'GRANADA',
  'GILET'                            : 'COLETE',
  'GLASS'                            : 'VIDRO',
  'GLOVES'                           : 'LUVAS (MALHA OU TECIDO)',
  'GOATSKIN'                         : 'COURO DE CABRA',
  'GUM'                              : 'GOMA',
  'HAIRCLIP'                         : 'PRESILHA DE CABELO',
  'HANDBAGS'                         : 'BOLSA DE MAO',
  'HANGER'                           : 'CABIDE',
  'HOBO BAG'                         : 'BOLSA',
  'HOLDER'                           : 'SUPORTE',
  'INSET'                            : 'INSERIDO',
  'INSOLE'                           : 'PALMILHAS',
  'JACKET'                           : 'CASACO OU BLAZER',
  'JEANS'                            : 'CALÇA',
  'JUMP SUIT'                        : 'MACACAO (MALHA OU TECIDO)',
  'JUTE'                             : 'JUTA',
  'KNIT TOP'                         : 'TOP DE MALHA',
  'LACE UP'                          : 'BOTAS',
  'LAMBSKIN'                         : 'COURO DE CORDEIRO',
  'LARGE SHOPPING >30CM'             : 'BOLSA',
  'LEATHER WOMAN BELT'               : 'CINTO',
  'LINEN'                            : 'LINHO',
  'LINING'                           : 'FORRO',
  'L-LONG WALLET'                    : 'CARTEIRA',
  'MAGNETIZED MATERIAL'              : 'MATERIAL MAGNETIZADO',
  'MANNQ ACCESS'                     : 'MANEQUIM',
  'MANNQ PARTS'                      : 'MANEQUIM',
  'MANNQ SET PARTS'                  : 'MANEQUIM',
  'MARY JANES'                       : 'SAPATILHAS',
  'MED. DENSITY FIBERBOARD'          : 'MDF',
  'MESSENGER BAG'                    : 'BOLSA MENSAGEIRO',
  'METALLISED FIBER'                 : 'FIBRA METALIZADA',
  'MISCELLANEOUS BAG'                : 'BOLSA',
  'M-MEDIUM WALLET'                  : 'CARTEIRA',
  'MULES'                            : 'MULES',
  'NATURAL FIBER'                    : 'FIBRA NATURAL',
  'NECKLACE'                         : 'COLAR',
  'O-ACCESSOIRE DE SAC'              : 'BOLSA',
  'O-CARD HOLDER'                    : 'PORTA-CARTÃO',
  'O-COIN PURSE'                     : 'PORTA-MOEDAS',
  'O-OTHER BELT BAG'                 : 'BOLSA CINTO NCM 4202.9',
  'O-OTHER SHAPE WITH CHAIN'         : 'BOLSA',
  'O-PORTE MONNAIE A BAND'           : 'BOLSA',
  'O-PURSEVANITY'                    : 'BOLSA',
  'OTHER FIBRES'                     : 'OUTRAS FIBRAS',
  'OTHER OPEN SHOES'                 : 'SAPATO ABERTO',
  'OUTER SOLE'                       : 'SOLA',
  'OVAL SUNGLASSES'                  : 'OCULOS DE SOL',
  'O-VANITY A BANDOULIERE'           : 'BOLSA',
  'PADDING'                          : 'PREENCHIMENTO',
  'PANTOS SUNVIDROES'                : 'OCULOS DE SOL',
  'PANTS'                            : 'CALÇA',
  'PAPER'                            : 'PAPEL',
  'PAREMENTURE'                      : 'FRENTE',
  'PARKA'                            : 'PARKA',
  'PATTE DE POCHE'                   : 'ABA DE BOLSO',
  'PATTE'                            : 'CARCETE',
  'PEARL'                            : 'PEROLA',
  'PEROLAY PEROLAY'                  : 'PEROLA PEROLA',
  'PHEASANT FEATHER'                 : 'PENA DE FAISÃO',
  'PHONE HOLDER WITH CHAIN'          : 'PORTA CELULAR',
  'PILOT SUNVIDROES'                 : 'OCULOS DE SOL',
  'PLASTIC'                          : 'PLASTICO',
  'PLATEAU'                          : 'PLATO',
  'POCKETING FABRIC'                 : 'TECIDO DO BOLSO',
  'POLYAMIDE'                        : 'POLIAMIDA',
  'POLYESTER'                        : 'POLIESTER',
  'POLYETHYLENE TEREPHTALATE'        : 'TEREFTALATO DE POLIETILENO',
  'POLYMETHYL METHACRYLATE'          : 'METACRILATO DE POLIMETILA',
  'POLYPROPYLENE'                    : 'POLIPROPILENO',
  'POLYURETHANE THERMOPLAST.'        : 'POLIURETANO TERMOPLASTICO',
  'POLYURETHANE'                     : 'POLIURETANO',
  'PORTE MONNAIE A CHAINE'           : 'BOLSA',
  'PORTE MONNAIE SANS CHAINE'        : 'CARTEIRA',
  'REAL FUR'                         : 'COURO AUTENTICO',
  'RECTANGLE SUNVIDROES'             : 'OCULOS DE SOL',
  'RESIN'                            : 'RESINA',
  'RHINESTONE'                       : 'STRASS',
  'RIBBINGS'                         : 'NERVURAS',
  'RING'                             : 'ANEL',
  'RISER'                            : 'DISPLAY EXPOSITOR',
  'ROCK CRYSTAL'                     : 'PEDRA DE CRISTAL',
  'ROUND SUNVIDROES'                 : 'OCULOS DE SOL',
  'RUBBER'                           : 'BORRACHA',
  'SANDALS'                          : 'SANDALIAS',
  'SCARF'                            : 'CACHECOL',
  'SET DE PLAGE'                     : 'BOLSA DE MAO',
  'SHEEPSKIN'                        : 'COURO DE CARNEIRO',
  'SHIELD SUNVIDROES'                : 'OCULOS DE SOL',
  'SHIRT'                            : 'CAMISA',
  'SHOES'                            : 'SAPATO',
  'SHORT BOOTS'                      : 'BOTAS',
  'SHORT FORRO'                      : 'FORRO CURTO',
  'SILK'                             : 'SEDA',
  'SKIRT'                            : 'SAIA',
  'SLEEVES'                          : 'MANGAS',
  'SLG ON CHAIN'                     : 'BOLSA',
  'SLIM BANDEAU'                     : 'BANDEAU PEQUENO',
  'SLINGS'                           : 'SANDALIAS',
  'SMALL LEATHER GOODS'              : 'BOLSA',
  'SMALL SHOPPING <31CM'             : 'BOLSA',
  'SMALL WALLET'                     : 'CARTEIRA PEQUENA',
  'SNEAKERS'                         : 'TENIS',
  'SQUARE CACHECOL'                  : 'CACHECOL',
  'SQUARE SUNVIDROES'                : 'OCULOS DE SOL',
  'S-SMALL CASE'                     : 'BOLSA PEQUENA',
  'STAINLESS STEEL'                  : 'AÇO INOXIDÁVEL',
  'STOLE'                            : 'ESTOLA',
  'STRAIGHT PANT'                    : 'CALÇA RETA',
  'STRAP'                            : 'ALÇA',
  'STRAW'                            : 'PALHA',
  'SUNGLASSES'                       : 'OCULOS DE SOL',
  'SUPPORT'                          : 'SUPORTE',
  'SWIMMING TOP'                     : 'TOP DE NATAÇÃO',
  'SWIMMING TRUNK'                   : 'SHORT DE BANHO',
  'TEE-SHIRT'                        : 'CAMISA',
  'THERMOPLAST.'                     : 'TERMOPLASTICO',
  'THONGS'                           : 'SANDALIAS',
  'TOP'                              : 'TOP',
  'TRAY'                             : 'BANDEJA',
  'TRUNK FORRO'                      : 'FORRO',
  'UPPER'                            : 'SUPERIOR',
  'UPSIDE'                           : 'SUPERIOR',
  'VANITY A CHAINE'                  : 'BOLSA',
  'VEAU VELOURS'                     : 'CAMURÇA DE BEZERRO',
  'VELOURS SYNTHETIQUE'              : 'VELUDO',
  'VERRES'                           : 'LENTES',
  'VEST'                             : 'COLETE',
  'WATER PAINT'                      : "TINTA A BASE D'AGUA",
  'WIDE LEG PANT'                    : 'CALÇA LARGA',
  'WITH HANDLE'                      : 'COM ALÇA',
  'WOOD'                             : 'MADEIRA',
  'WOOL'                             : 'LA',
  'Long'                             : 'LONGO',
  'WOVEN'                            : 'TECIDO PLANO',
  'Straight'                         : 'RETÍLINEA',
  'FORRO: Full'                      : 'FORRO COMPLETO',
  'CALF GRAIN LEATHER (BOS TAURUS)'  : 'COURO BOVINO',
  'COW GRAIN LEATHER (BOS TAURUS)'   : 'COURO BOVINO',
  'Above knee'                       : 'ACIMA DO JOELHO',
  'Half lined'                       : 'MEIO FORRO',
  'LAMB LEATHER (OVIS ARIES ARIES)'  : 'COURO DE CORDEIRO',
};

// Regras de limpeza (campos removidos condicionalmente) — de limpeza_tratamento no script original.
const REGRAS_LIMPEZA = {
  'COMPRIMENTO': ['CASACO', 'CARDIGA', 'CAMISETA', 'CAMISA', 'BOLSA', 'PORTA CARTAO', 'CALCA', 'SUETER', 'ECHARPE', 'LENCO', 'CINTO'],
  'FORRO'      : ['ECHARPE', 'LENCO', 'CINTO', 'OCULOS', 'VELA'],
  'MANGA'      : ['OCULOS', 'VELA'],
  'MALHA'      : ['OCULOS', 'VELA', 'BRACELETE', 'BRINCO', 'COLAR'],
  'SOLA'       : ['CASACO', 'CARDIGA', 'CAMISETA', 'CAMISA', 'BOLSA', 'PORTA CARTAO', 'CALCA', 'SUETER', 'ECHARPE', 'LENCO', 'CINTO', 'OCULOS', 'VELA'],
};

const PADRAO_REMOCAO = ['(CANADA ONLY)', '(FOR FILLING ONLY)'];
